name: amt-eval-miniconda
channels:
    - conda-forge
    - pytorch
    - nvidia
    - defaults
dependencies:
    - jupyter
    - librosa=0.9.2
    - pandas=1.4.2
    - python=3.10.0
#     # todo test if this pip dependency is ok
    - pip=24.2
    - pytest=8.3.5
    - pytorch
    - torchvision
    - torchaudio
    - tqdm=4.67.1
    - pytorch-cuda=12.4
    - pretty_midi=0.2.9
    - pip:
        - mir-eval==0.8.2
        - soundfile==0.12.1
        - basic-pitch==0.4.0
